import { mergeStyleSets } from "@fluentui/react/lib/Styling";

export const classNames = mergeStyleSets({
  header: {
    height: "60px",
    backgroundColor: "#26262D",
    display: "flex",
    alignItems: "center",
    color: " #008B98",
    // position: "fixed",
    // zIndex: 1010,
    // top: 0,
    // right: 0,
    // left: 0,
  },
  mainLogo: {
    width: "156px",
    marginLeft: "24px",
  },
  hamberger: {
    width: " 3.125%",
    height: "100%",
    backgroundColor: "#141414",
    position: "relative",
    textAlign: "center",
    cursor: "pointer",
  },
  hambergerIcon: {
    color: "#999",
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    margin: "auto",
  },
  headerRight: {
    height: "100%",
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  updateInfo: {
    fontSize: "14px",
  },
  refreshIcon: {
    cursor: "pointer",
  },
  defaultBtn: {
    border: "1px solid #008B98",
    boxSizing: "border-box",
    borderRadius: "50px",
    color: " #008B98",
    backgroundColor: " #26262D",
    cursor: "pointer",
    padding: "18px",
    margin: "0 16px",
    selectors: {
      "&:hover": {
        backgroundColor: "#383838",
        color: "#008B98",
      },
      "&:active": {
        backgroundColor: "#383838",
        color: "#008B98",
      },
    },
  },
  userDropdown: {
    width: "220px",
    height: "100%",
    color: "#ccc",
    backgroundColor: "#141414",
    cursor: "pointer",
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    span: {
      fontSize: "12px",
      color: "#999",
    },
  },
  profileIcon: {
    borderRadius: "50%",
    padding: "10px",
    backgroundColor: "#333D3D",
    color: " #008B98",
    fontFamily: "roboto-bold",
    fontWeight: "normal",
    fontSize: "14px",
    marginLeft: "5px",
  },
  userDropOptions: {
    width: "220px",
    position: "absolute",
    top: "60px",
    right: 0,
    zIndex: 2,
    backgroundColor: "#141414",
    li: {
      height: "60px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      paddingRight: "20px",
      backgroundColor: "transparent",
      fontSize: "14px",
      color: "#999",
      cursor: "pointer",
      "&:hover": {
        backgroundColor: "#333d3d",
      },
      span: {
        paddingRight: "10px",
      },
    },
  },
});
