export const FETCH_TODOS_REQUESTED = 'FETCH_TODOS_REQUESTED';
export const FETCH_TODOS_SUCCEEDED = 'FETCH_TODOS_SUCCEEDED';
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';
export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const ADD_TODO_SUCCEEDED = 'ADD_TODO_SUCCEEDED';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';