export const FETCH_SERVICE_NOTIFICATIONS = 'FETCH_SERVICE_NOTIFICATIONS';
export const SET_SERVICE_NOTIFICATIONS = 'SET_SERVICE_NOTIFICATIONS';
export const SET_SELECTED_TICKET = 'SET_SELECTED_TICKET'
export const FETCH_SERVICE_NOTIFICATIONS_CONFIGURATIONS = 'FETCH_SERVICE_NOTIFICATIONS_CONFIGURATIONS';
export const SET_SERVICE_NOTIFICATIONS_CONFIGURATIONS = 'SET_SERVICE_NOTIFICATIONS_CONFIGURATIONS';
export const CREATE_SERVICE_NOTIFICATIONS = 'CREATE_SERVICE_NOTIFICATIONS'
