const NAMESPACE = 'UNIT_OVERVIEW';
export const UNIT_OVERVIEW_FETCH_UNITS = `UNIT_OVERVIEW_FETCH_UNITS`;
export const UNIT_OVERVIEW_FETCH_UNITS_SUCCEEDED = `UNIT_OVERVIEW_FETCH_UNITS_SUCCEEDED`;
export const UNIT_OVERVIEW_FETCH_UNITS_FAILED = `UNIT_OVERVIEW_FETCH_UNITS_FAILED`;
