const NAMESPACE = 'UNIT_SERVICE_NOTIFICATIONS';
export const UNIT_FETCH_SERVICE_NOTIFICATIONS = `UNIT_FETCH_SERVICE_NOTIFICATIONS`;
export const UNIT_FETCH_SERVICE_NOTIFICATIONS_SUCCEEDED = `UNIT_FETCH_SERVICE_NOTIFICATIONS_SUCCEEDED`;
export const UNIT_FETCH_SERVICE_NOTIFICATIONS_FAILED = `UNIT_FETCH_SERVICE_NOTIFICATIONS_FAILED`;
