const NAMESPACE = 'UNIT_AEE';
export const UNIT_FETCH_AEE = `UNIT_OVERVIEW_FETCH_UNITS`;
export const UNIT_FETCH_AEE_SUCCEEDED = `UNIT_OVERVIEW_FETCH_UNITS_SUCCEEDED`;
export const UNIT_FETCH_AEE_FAILED = `UNIT_OVERVIEW_FETCH_UNITS_FAILED`;
